import java.util.Arrays;
public class Sıralama {
    public static void main(String[] args) {
       String [] array={
       "HUMPTY SHARMA KI DULHANIA",
       "JOHN WICK",
       "YOU ARE BEAUTIFUL",
       "DEADLY CLASS",
       "HAYALET SUVARI",
       "BASLANGIC",
       "TAKERS",
       "SWAT FIREFIGTH",
       "WANTED TAU",
       "WHO KILLED SARA",
       "OLDURME ARZUSU",
       "BLACKHAT",
       "ATLANTIK SAVASI",
       "CATCH ME IFYOU CAN",
       "PARAZIT",
       "NOBETCI",
       "BLACKLIST",
       "ALICE",
       "SNOWPIERCER",
       "KARDAKI IZLER",
       "DUNYADAN HABERLER",
       "MATRIX",
       "MY SPY",
       "YILDIZLARASI",
       "START UP",
       "BODYGUARD",
       "%3",
       "THE RAIN",
       "SPACE FORCE",
       "TO THE LAKE",
       "TELEFON",
       "CASUSULUK SANATI",
       "THE SKY IS PINK",
       "FORREST GUMP",
       "EQUINOX",
       "BERRAK GOL",
       "HUDSON HAWK",
       "DRACULA UNTOLD",
       "TRINHANGA",
       "THE PRESTIGE",
       "12 MAYMUN",
       "CONSTANTINE",
       "47 RONIN",
       "ATESBOCEGI YOLU",
       "PENCEREDEKI KADIN",
       "ALIVE",
       "LUPIN",
       "12 STRONG",
       "BRIDGE OF SPIES",
       "SHUTTER ISLAND",
       "ALEX RIDER",
       "NEW BLOOD",
       "MY NAME",
       "SQUID GAME",
       "GOBLIN",
       "BLACK WIDOW",
       "OUTH OF DEATH",
       "DA VINCI SIFRESI",
       "ANGELS AND DEMONS",
       "CEHENNEM",
       "KIN",
       "KAPI",
       "NASIPSE ADAYIZ",
       "GELINCIK",
       "ACI KIRAZ",
       "ANOTHER LIFE",
       "THE MORNING SHOW",
       "PEAKY BLINDERS",
       "SISPHUS:THE MYTH",
       "LOVE IS SWEET",
       "UPLOADED",
       "RED NOTICE",
       "KEEPING UP WITH THE JONESES",
       "THE CHORONICLES OF EVIL",
       "KULUP",
       "TALE OF NINE TAILED",
       "TOUCH YOUR HEART",
       "JIRISAN",
       "MR. ROBOT",
       "THE ART OF SELF DEFENCE",
       "AVCI: KIS SAVASI",
       "BUSTED",
       "AD VITAM",
       "ORANGE ISS THE NEW BLACK",
       "ANNE WITH AN'E",
       "CIZGILI PIJAMALI COCUK",
       "THE FALL",
       "SILIKON VADISININ KORSANLARI",
       "HACKERS",
       "HAPPINESS",
       "SILENCED",
       "VINCENZO",
       "LIFE",
       "HOTEL KING",
       "HELLBOUND",
       "VAGABOND",
       "THE SILENT SEA",
       "DR.BRAIN",
       "BAD AND CRAZY",
       "INTIKAM MANYEO",
       "HEALER",
       "TRAIN TO BUSAN",
       "STRONG GIRL BONG SOON",
       "KILL ME HEAL ME",
       "LAWLESS LAWYER",
       "DR.ROMANTIC",
       "THE DEVIL JUDGE",
       "MOUSE",
       "BEYOND EVIL",
       "DEFENDANT",
       "DOCTOR JOHN",
       "DP",
       "MY MISTER",
       "ARE YOU HUMAN",
       "HOSPITAL PLAYLIST",
       "DOCTOR GHOST",
       "THE POLICEMANS LINEAGE",
       "MAN TO MAN",
       "BABAMIN KEMANI",
       "DUEL",
       "PRISON PLAYBOOK",
       "STRANGER",
       "PARTNERS JUSTICE",
       "LAW SCHOOL",
       "A BUSINESS PROPOSAL",
       "GRID",
       "MILITARY PRESECUTOR DOBERMAN",
       "CRAZY LOVE",
       "THE SOUND OF MAGIC",
       "SHOOTING STARS",
       "FROM NOW ON SHOWTIME",
       "AGAIN MAY LIFE",
       "TOMORROW",
       "OUR BLUES",
       "LOVE ALL PLAY",
       "THE KINGS AFFECTION",
       "POLICE UNIVERSTY",
       "MEZARLIK",
       "KUS UCUSU",
       "WHY HER",
       "DOCTOR LAWYER",
       "MY LIBRATION NOTES",
       "KILL HELL",
       "EXTRAORDINARY ATTORNEY WOO",
       "ENTERTAINER",
       "PASTA",
       "BIG MOUTH",
       "ADAMAS",
       "TODAYS WEBTOON",
       "IF YOU WISH UPON ME",
       "LITTLE WOMAN",
       "GOOD JOB",
       "THE GOOD DETECTIVE",
       "SEE",
       "THE LAW CAFE",
       "HWARANG",
       "ONE DOLLAR LAWYER",
       "NARCO SAINES",
       "RECIPE FOR FAREWELL",
       "UNLOCK MY BOSS",
       "CONNECT",
       "EMERGANCY DECLARATION",
       "REBORN RICH",
       "ALCHEMY OF SOULS",
       "CAN WE BE STRANGERS",
       "TROLLEY " ,
       "THE INTEREST OF LOVE",
       "WOK OF LOVE",
       "WEDNESDAY",
       "GLITCH"
       
       
       };
       Arrays.sort(array);
       for(String isimler : array){
        System.out.println(isimler);
       }

    }
}
